== qlic

qlic is an unecessarily fast cli frontend to the venereal Zoho cliq. It is cliq but unopinionated.

NOTE: This project follows 'README driven development', so some of what is said in 'What Works' section actually doesn't work. I will add a CHANGELOG in the future with proper versioning.

=== Why?

I would rather use the comfy terminal than a web browser for my computing needs. Zoho cliq was my only reason for opening a tab in browser. Not anymore.

=== TODO

- Make qlic interactive/usable by making it filesystem based like https://git.suckless.org/ii/file/README.html?q=label:%22ii%22.

=== Usage
==== Setup

For qlic to work, you need client id and secret which can be obtained from https://api-console.zoho.com/ and should be
substituted in $XDG_DATA_HOME/qlic/config.json

	{
		"client_id": "<zoho_client_id>",
		"client_secret": "<zoho_client_secret>"
	}

`qlic -a` should be runned for the first time to authenticate the application.

You need to get chat_id of the user of whom you want to send or recieve messages. You can get chat_id using the contacts API.

==== Sending a text

	qlic -s "Hey! qlic is cliq" chat_id
	echo "Pipes are awesome!" | qlic -s - chat_id

==== Sending an attachment

	qlic -b image.jpg chat_id

==== Receive chat from multiple users

	qlic -r chat_id [clientid...]

=== What works

* Authentication via OAuth
* Receive and send text to chat, channels
* Receive and send attachments to chat, channels

=== What doesn't work

* Cliq call - Cliq doesn't provide any API to for this feature.

=== Install

	git clone https://github.com/bharatvaj/qlic
	cd qlic
	make install

=== Dependencies

* libcurl
* bharatvaj/OAuth2
* zserge/jsmn

NOTE: qlic will save it's state file under ~/.cache/. Make sure the directory is available.

== qlic on windows
Due to curl not compiling with MSVC. qlic will be a mingw app as curl is available as mingw. Make sure to compile qlic statically as the users might need to run it without any additional runtime.
